### ISSUE TITLE
请问这个问题如何处理呢

### ISSUE THREAD

**Issue by jinyue233** [liuyukuai/dis#1]
// 此处服务器断电如何处理？单位时间请求无法处理? TODO

**Comment by liuyukuai** [comment]
> // 此处服务器断电如何处理？单位时间请求无法处理? TODO

1、业务系统至少需要两个节点
2、断电业务系统事务会回滚，需要额外设置redis存储对象初始状态（比如-1），不能是简单字符串，业务成功后需要更新状态（比如更新为1）。
3、验证时需要判断状态（1：不通过，-1：通过）

**Comment by liuyukuai** [comment]
> 1、业务系统至少需要两个节点
> 2、断电业务系统事务会回滚，需要额外设置redis存储对象初始状态（比如-1），不能是简单字符串，业务成功后需要更新状态（比如更新为1）。
> 3、验证时需要判断状态（1：不通过，-1：通过）
